use_default_settings: true

server:
  port: 8080
  bind_address: "0.0.0.0"
  limiter: false
  secret_key: "DGg1zObN2XgAFzmd4326cVFE8AZRewu"

search:
  safe_search: 0
  autocomplete: ""
  formats:
    - html
    - json

ui:
  default_theme: simple
  query_in_title: false
  center_alignment: false
  default_locale: ""
  theme_args:
    oscar_style: logicodev
